
import '../globals.css'
import React, { ReactNode } from 'react'
import RootHeader from '@/components/template/root/RootHeader'
import RootFooter from '@/components/template/root/RootFooter'





export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
type Props = {
  children: string | JSX.Element | JSX.Element[]| ReactNode 
}
export default function RootLayout({ children }:Props) {
  return (
    <html lang="fa" dir='rtl'>
      <meta charSet="UTF-8"></meta>
      <body>
    <RootHeader />
        {children}
        <RootFooter />
        </body>
    </html>
  )
}
