import { Inter } from 'next/font/google'
import '../globals.css'
import React, { ReactNode } from 'react'
import RootHeader from '@/components/template/root/RootHeader'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
type Props = {
  children: string | JSX.Element | JSX.Element[]| ReactNode 
}
export default function RootLayout({ children }:Props) {
  return (
    <html lang="fa" dir='rtl'>
      <meta charSet="UTF-8"></meta>
      <body className={inter.className}>
    <RootHeader />
        {children}
        
        </body>
    </html>
  )
}
